The Nobel Prize has been among the most prestigious international awards since 1901. Each year, awards are bestowed in chemistry, literature, physics, physiology or medicine, economics, and peace. In addition to the honor, prestige, and substantial prize money, the recipient also gets a gold medal with an image of Alfred Nobel (1833 - 1896), who established the prize.

![](Nobel_Prize.png)

The Nobel Foundation has made a dataset available of all prize winners from the outset of the awards from 1901 to 2023. The dataset used in this project is from the Nobel Prize API and is available in the `nobel.csv` file in the `data` folder.

In this project, you'll get a chance to explore and answer several questions related to this prizewinning data. And we encourage you then to explore further questions that you're interested in!

In [112]:
# Loading in required libraries
import pandas as pd
import seaborn as sns
import numpy as np

# Start coding here!

In [113]:
nobel = pd.read_csv('data/nobel.csv')
print(nobel.head())
nobel.info()

   year    category  ... death_city death_country
0  1901   Chemistry  ...     Berlin       Germany
1  1901  Literature  ...   Châtenay        France
2  1901    Medicine  ...    Marburg       Germany
3  1901       Peace  ...     Heiden   Switzerland
4  1901       Peace  ...      Paris        France

[5 rows x 18 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   year                  1000 non-null   int64
 1   category              1000 non-null   object
 2   prize                 1000 non-null   object
 3   motivation            912 non-null    object
 4   prize_share           1000 non-null   object
 5   laureate_id           1000 non-null   int64
 6   laureate_type         1000 non-null   object
 7   full_name             1000 non-null   object
 8   birth_date            968 non-null    object
 9   birth_city            964 non-null    object
 10  birth_country         969 non-null    object
 11  sex                   970 non-null    object
 12  organization_name     736 non-null    object
 13  organization_city     735 non-null    object
 14  organization_country  735 non-null    object
 15  death_date            596 non-null    object
 16  death_city            579 non-null    object
 17  death_country         585 non-null    object
dtypes: int64(2), object(16)
memory usage: 140.8+ KB

In [114]:
top_gender = str(nobel['sex'].value_counts().index[0])
top_country = str(nobel['birth_country'].value_counts().index[0])
print(f"{top_gender}\n{top_country}")

Male
United States of America

In [115]:
nobel['decade'] = (nobel['year'] // 10)*10 # make decades col

countries_decades_count = nobel.groupby("decade")['birth_country'].count().astype(int)

usa_count = nobel[nobel['birth_country']=='United States of America'].groupby('decade')['birth_country'].count().astype(int)

ratio = usa_count / countries_decades_count

max_decade_usa = int(ratio.idxmax())
print(max_decade_usa)

2000

In [116]:
female_laurettes = nobel[nobel['sex']=='Female']\
.groupby(['category', 'decade'])['sex'].value_counts().astype(float)

male_laurettes = nobel[nobel['sex']=='Male']\
.groupby(['category', 'decade'])['sex'].value_counts().astype(float)

female_df = pd.DataFrame(female_laurettes).droplevel('sex')
male_df = pd.DataFrame(male_laurettes).droplevel('sex')

female_df.columns = ['count']
male_df.columns = ['count']
# print(female_df.head(), male_df.head())

both_sexes = female_df.merge(male_df, how='outer', suffixes=["_f", "_m"], on=['category', 'decade'])
both_sexes['ratio'] = both_sexes['count_f'] / both_sexes['count_m']

#print(both_sexes)

most_f_l = both_sexes.idxmax() # returns the max indexes in multi index for all 3 fields
# print(most_f_l)

cat, dec = most_f_l['ratio']
print(f"{cat}, {dec}")
max_female_dict = {dec: cat}

print(max_female_dict)

Literature, 2020
{2020: 'Literature'}

In [117]:
first_woman = nobel[nobel['sex']=='Female']\
.sort_values(by='year')[['category', 'full_name']].iloc[0]

first_woman_name = first_woman['full_name']
first_woman_category = first_woman['category']

print(first_woman_name, first_woman_category)

Marie Curie, née Sklodowska Physics

In [118]:
count_names = nobel['full_name'].value_counts()
count_names = count_names[count_names > 1]

repeat_list = list(count_names.index)

print(repeat_list)

['Comité international de la Croix Rouge (International Committee of the Red Cross)', 'Linus Carl Pauling', 'John Bardeen', 'Frederick Sanger', 'Marie Curie, née Sklodowska', 'Office of the United Nations High Commissioner for Refugees (UNHCR)']